#!/usr/bin/env node
/**
 * Generate presets/standard-inspect.patch.yml: a copy of the dsh web app's
 * shipped `standard` agent preset whose own workflow engine runs one sub-agent
 * at a time. dsh-inspect itself is mounted host-wide by cordis.patch.yml, so
 * its tools appear in every preset; --mount-inspect additionally mounts a copy
 * inside this preset's delegation group, next to its isolated engine.
 *
 * The web app keeps one workflow engine per agent preset, isolated to the
 * preset's delegation group; a workflow consumer outside that group cannot see
 * it. Loader patches cannot reach inside a shipped preset, so this preset is a
 * copy of `standard` — re-run this script after every dsh update so the copy
 * follows the new `standard`.
 *
 * Usage:
 *   node scripts/gen-preset.mjs [path/to/dsh-web-app/presets/standard.patch.yml]
 *     [--max-concurrent-agents N]
 * Without a path it looks for @deepseek-ai/dsh-web-app next to the globally
 * installed `dsh` (npm root -g).
 */
import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const argv = process.argv.slice(2)
let maxConcurrent = 1
// dsh-inspect is mounted host-wide (cordis.patch.yml), so its tools reach every
// preset; pass --mount-inspect to also mount a copy inside this preset.
const mountInspect = argv.includes('--mount-inspect')
if (mountInspect) argv.splice(argv.indexOf('--mount-inspect'), 1)
const mi = argv.indexOf('--max-concurrent-agents')
if (mi !== -1) {
  maxConcurrent = Number(argv[mi + 1])
  if (!Number.isInteger(maxConcurrent) || maxConcurrent < 0) throw new Error('--max-concurrent-agents takes an integer ≥ 0 (0 = engine default)')
  argv.splice(mi, 2)
}

function findStandard() {
  if (argv[0]) return argv[0]
  const globalRoot = execSync('npm root -g', { encoding: 'utf8' }).trim()
  for (const dir of [
    join(globalRoot, '@deepseek-ai', 'dsh', 'node_modules', '@deepseek-ai', 'dsh-web-app'),
    join(globalRoot, '@deepseek-ai', 'dsh-web-app'),
  ]) {
    const file = join(dir, 'presets', 'standard.patch.yml')
    if (existsSync(file)) return file
  }
  throw new Error('could not find @deepseek-ai/dsh-web-app/presets/standard.patch.yml — pass its path')
}

const sourcePath = findStandard()
const webAppVersion = (() => {
  try { return JSON.parse(readFileSync(join(dirname(sourcePath), '..', 'package.json'), 'utf8')).version } catch { return 'unknown' }
})()
let text = readFileSync(sourcePath, 'utf8').replace(/\r\n/g, '\n')

/** Replace exactly one occurrence, failing loudly if the shipped layout changed. */
function replaceOnce(pattern, replacement, what) {
  const matches = text.match(new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : pattern.flags + 'g'))
  if (!matches || matches.length !== 1) {
    throw new Error(`standard preset layout changed: expected exactly one ${what}, found ${matches ? matches.length : 0} — update scripts/gen-preset.mjs`)
  }
  text = text.replace(pattern, replacement)
}

text = text.slice(text.indexOf('- insert:'))
replaceOnce(/^( +)- id: preset-standard$/m, '$1- id: preset-standard-inspect', 'preset-standard row')
replaceOnce(/^( +)id: standard\n/m, (_m, ind) =>
  `${ind}id: standard-inspect\n${ind}name: Standard + inspect\n${ind}description: The standard agent with the workflow engine running one sub-agent at a time.\n`,
  'preset id')
replaceOnce(/^( +)order: (\d+)\n/m, (_m, ind, n) => `${ind}order: ${Number(n) + 10}\n`, 'preset order')
// The engine row inside the delegation group; add the concurrency limit and
// mount dsh-inspect right after the `tool-workflow` row that shares its realm.
replaceOnce(/^( +)- id: workflow-ptc\n\1  name: '@deepseek-ai\/dsh-workflow-ptc'\n\1  config:\n((?:\1    .*\n)+)/m,
  (_m, ind, cfg) => `${ind}- id: workflow-ptc\n${ind}  name: '@deepseek-ai/dsh-workflow-ptc'\n${ind}  config:\n${cfg}`
    + (maxConcurrent > 0 ? `${ind}    # Run workflow sub-agents one at a time (0 = engine default: CPU cores - 2, max 16).\n${ind}    maxConcurrentAgents: ${maxConcurrent}\n` : ''),
  'workflow-ptc row')
replaceOnce(/^( +)- id: tool-workflow\n\1  name: '@deepseek-ai\/dsh-tool-workflow'\n/m,
  (m, ind) => mountInspect ? `${m}${ind}# dsh-inspect shares this group's isolated workflowEngine.\n${ind}- id: dsh-inspect-preset\n${ind}  name: '@dsh-external/dsh-inspect'\n` : m,
  'tool-workflow row')
if (!/isolate:\n\s+workflowEngine: true/.test(text)) throw new Error('standard preset no longer isolates workflowEngine — check the new layout')

const header = `# GENERATED by scripts/gen-preset.mjs from @deepseek-ai/dsh-web-app ${webAppVersion}
# presets/standard.patch.yml — do not edit by hand; re-run the script after a dsh update.
#
# Agent preset "Standard + inspect": the shipped standard preset, with its own
# workflow engine limited to one sub-agent at a time. dsh-inspect's tools come
# from the host-wide mount in cordis.patch.yml and appear in every preset.
`
writeFileSync(join(root, 'presets', 'standard-inspect.patch.yml'), header + text)
console.log(`wrote presets/standard-inspect.patch.yml from ${sourcePath} (dsh-web-app ${webAppVersion})`)
